// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ1b-zhlgMi19d0Tm9m7Aau4DDsh580qc',
    appId: '1:284993879659:web:228ab7ee0a0e62cbf37b2e',
    messagingSenderId: '284993879659',
    projectId: 'jtn-insta',
    authDomain: 'jtn-insta.firebaseapp.com',
    storageBucket: 'jtn-insta.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKz0Zl4q6CGwk7Nk3AiZjAQYrems08wmM',
    appId: '1:284993879659:android:8a44418818510d67f37b2e',
    messagingSenderId: '284993879659',
    projectId: 'jtn-insta',
    storageBucket: 'jtn-insta.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUyoq1nq84dRX8FOJqrE-UbcW8mOs_dn4',
    appId: '1:284993879659:ios:21d8ad32ab47daf5f37b2e',
    messagingSenderId: '284993879659',
    projectId: 'jtn-insta',
    storageBucket: 'jtn-insta.appspot.com',
    iosClientId: '284993879659-hga7s95mna5j9grg9leiudboucnm66ut.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramFlutter',
  );
}
